In [1]:
import numpy as np
import pandas as pd

In [ ]:
def part(arr):
    pivot = arr[(len(arr))//2]
    print('pivot = ',(len(arr))//2)
    larr = []
    rarr = []
    for i in range(len(arr)):
        if arr[i] < pivot:
            larr.append(arr[i])
        elif arr[i] > pivot:
            rarr.append(arr[i])
    index = len(larr)
    return larr, rarr, index

In [15]:
part([1,3,2,10,5])

([1, 2], [3, 10, 5], 1)

In [ ]:
def kth_element(arr, k):
    while True:
        print(len(arr))
        larr, rarr, ind = part(arr)
        print(larr, rarr)
        if ind == k:
            return larr[ind-1]
        elif ind > k:
            arr = larr
        else: 
            arr = rarr

In [43]:
def test_stat(num_of_tests = 10):
    for test in range(num_of_tests):
        size = np.random.randint(2,20)
        arr_1d = np.random.randint(1, 100, size=size)
        k = np.random.randint(0,size-1)
        print(arr_1d)
        print(np.sort(arr_1d)[k])

In [44]:
test_stat(10)


[14 22 25]
14
[ 9 21 25 80  8 43  9  4 57 75 82 35 70 41 21 17]
17
[26 59 48 10 49 81 91]
59
[13 36 97 26 54]
26
[ 2 59 47 95]
47
[76 26 13 84]
26
[75 14  7 58 53 93 99 64 51 53 14 58 57  6 66  9 86 84]
7
[13 19  2 92 48 71 75 33 41 33  1 77 21]
13
[16 78 72 40 70 23 48 27 37  8 18 63]
37
[25 37 16 93 54 59 64 22]
25


In [32]:
kth_element([1,3,2,10,5],3)

5
pivot =  2
[1] [3, 2, 10, 5]
4
pivot =  2
[3, 2, 5] [10]


5